swagger: '2.0'
info:
  version: 0.0.1
  title: DataMiningCloud Repository Service
  description: An API specification of DMC Evaluation based on swagger-2.0 specification
  contact:
    name: Aid
    email: aid666@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
basePath: /evaluator
schemes:
  - https
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:

  /svcs/{svcKey}:
    get:
      tags:
      - svc
      - evaluation
      parameters:
      - in: path
        name: svcKey
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceEvaluation'
    post:
      tags:
      - svcs
      - input
      parameters:
      - in: path
        name: svcKey
        type: string
      - in: body
        name: body
        schema:
         $ref: "#/definitions/EvaluationData"
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/ServiceEvaluationMetadata'
    delete:
      tags:
      - svc
      - evaluation
      parameters:
        - in: path
          name: svcKey
          type: string
        - in: path
          name: evaKey
          type: string
      responses:
        "200":
          description: OK

  /svcs/{svcKey}/history/{evaKey}:
    get:
      tags:
      - svc
      - evaluation
      parameters:
      - in: path
        name: svcKey
        type: string
      - in: path
        name: evaKey
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ServiceEvaluation'
    delete:
      tags:
      - svc
      - evaluation
      parameters:
        - in: path
          name: svcKey
          type: string
        - in: path
          name: evaKey
          type: string
      responses:
        "200":
          description: OK

  /trainers/{trainerKey}:
    get:
      tags:
      - trainer
      - evaluation
      parameters:
      - in: path
        name: trainerKey
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TrainerEvaluation'
    post:
      tags:
      - svcs
      - input
      parameters:
      - in: path
        name: trainerKey
        type: string
      - in: body
        name: body
        schema:
         $ref: "#/definitions/EvaluationData"
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/TrainerEvaluationMetadata'
    delete:
      tags:
      - trainer
      - evaluation
      parameters:
        - in: path
          name: trainerKey
          type: string
        - in: path
          name: evaKey
          type: string
      responses:
        "200":
          description: OK

  /trainers/{trainerKey}/history/{evaKey}:
    get:
      tags:
      - trainer
      - evaluation
      parameters:
      - in: path
        name: trainerKey
        type: string
      - in: path
        name: evaKey
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TrainerEvaluation'
    delete:
      tags:
      - trainer
      - evaluation
      parameters:
        - in: path
          name: trainerKey
          type: string
        - in: path
          name: evaKey
          type: string
      responses:
        "200":
          description: OK

definitions:

  EvaluationData:
    properties:
      data:
        $ref: 'https://raw.githubusercontent.com/aid666/DataMiningCloud/master/swagger-api.yaml#/definitions/DMData'
      resultAttr:
        $ref: 'https://raw.githubusercontent.com/aid666/DataMiningCloud/master/swagger-api.yaml#/definitions/Attribute'

  ServiceEvaluationMetadata:
    properties:
      status:
        type: string
      datetime:
        type: string

  ServiceEvaluation:
    properties:
      metadata:
        $ref: '#/definitions/ServiceEvaluationMetadata'
      evaData:
        $ref: '#/definitions/EvaluationData'
      executionPeriod:
        type: string
      result:
        $ref: 'https://raw.githubusercontent.com/aid666/DataMiningCloud/master/swagger-api.yaml#/definitions/DMData'

  TrainerEvaluationMetadata:
    properties:
      status:
        type: string
      datetime:
        type: string
      evaType:
        description: 10-crosses evaluation? or n-crosses?
        type: string

  TrainerEvaluation:
    properties:
      metadata:
        $ref: '#/definitions/TrainerEvaluationMetadata'
      evaData:
        $ref: '#/definitions/EvaluationData'
      executionPeriod:
        type: string
      result:
        $ref: 'https://raw.githubusercontent.com/aid666/DataMiningCloud/master/swagger-api.yaml#/definitions/DMData'
