swagger: '2.0'
info:
  version: 0.0.1
  title: DataMiningCloud Evaluation Service
  description: An API specification of DMC Evaluation based on swagger-2.0 specification
  contact:
    name: Aid
    email: aid666@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
basePath: /evaluator
schemes:
  - http
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
paths:
  /processers/{catalog}/{svcKey}:
    get:
      tags:
      - svc
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: svcKey
        type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceEvaluation'
    post:
      tags:
      - svc
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: svcKey
        type: string
      - in: body
        name: body
        schema:
         $ref: "#/definitions/EvaluationData"
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/ServiceEvaluationMetadata'
    delete:
      tags:
      - svc
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: svcKey
        type: string
      responses:
        204:
          description: OK

  /processers/{catalog}/{svcKey}/history/{evaKey}:
    get:
      tags:
      - svc
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: svcKey
        type: string
      - in: path
        name: evaKey
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ServiceEvaluation'
    delete:
      tags:
      - svc
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: svcKey
        type: string
      - in: path
        name: evaKey
        type: string
      responses:
        "200":
          description: OK

  /trainers/{catalog}/{trainerKey}:
    get:
      tags:
      - trainer
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: trainerKey
        type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TrainerEvaluation'
    post:
      tags:
      - trainer
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: trainerKey
        type: string
      - in: body
        name: body
        schema:
         $ref: "#/definitions/TrainerEvaluationData"
      responses:
        200:
          description: OK
          schema:
              $ref: '#/definitions/TrainerEvaluationMetadata'
    delete:
      tags:
      - trainer
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: trainerKey
        type: string
      responses:
        204:
          description: OK

  /trainers/{catalog}/{trainerKey}/history/{evaKey}:
    get:
      tags:
      - trainer
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: trainerKey
        type: string
      - in: path
        name: evaKey
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TrainerEvaluation'
    delete:
      tags:
      - trainer
      parameters:
      - in: path
        name: catalog
        type: string
      - in: path
        name: trainerKey
        type: string
      - in: path
        name: evaKey
        type: string
      responses:
        "200":
          description: OK

definitions:
  Domain:
    properties:
      name:
        type: string
      date:
        description: The domain in differnent date may different, think about the change of computer brand from 1995 to 2015 .
        type: string
      parentDomain:
        $ref: '#/definitions/Domain'

  DMData:
    properties:
      key:
        type: string
      data:
        type: array
        items:
         $ref: '#/definitions/ColumnData'

  ColumnData:
    properties:
      attribute:
        $ref: '#/definitions/Attribute'
      data:
        type: array
        items:
          type: string

  DataInfor:
    properties:
      name:
        type: string
      domain:
        $ref: '#/definitions/Domain'

  Attribute:
    properties:
      name:
        type: string
      type:
        type: string
      format:
        type: string
      dataInfor:
        $ref: '#/definitions/DataInfor'

  EvaluationData:
    properties:
      data:
        $ref: '#/definitions/DMData'
      resultAttr:
        $ref: '#/definitions/Attribute'

  TrainerEvaluationData:
    properties:
      data:
        $ref: '#/definitions/DMData'
      resultAttr:
        $ref: '#/definitions/Attribute'
      crossNumber:
        type: integer

  ServiceEvaluationMetadata:
    properties:
      status:
        type: string
      datetime:
        type: string

  ServiceEvaluation:
    properties:
      metadata:
        $ref: '#/definitions/ServiceEvaluationMetadata'
      evaData:
        $ref: '#/definitions/EvaluationData'
      executionPeriod:
        type: string
      result:
        $ref: '#/definitions/DMData'

  TrainerEvaluationMetadata:
    properties:
      status:
        type: string
      datetime:
        type: string
      evaType:
        description: 10-crosses evaluation? or n-crosses?
        type: string

  TrainerEvaluation:
    properties:
      metadata:
        $ref: '#/definitions/TrainerEvaluationMetadata'
      evaData:
        $ref: '#/definitions/EvaluationData'
      executionPeriod:
        type: string
      result:
        $ref: '#/definitions/DMData'
